# Generated by Django 5.0.4 on 2024-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_model',
            name='on_time_delivery_rate',
            field=models.FloatField(max_length=60, null=True),
        ),
    ]
