# Generated by Django 5.0.4 on 2024-05-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_vender_model_on_time_delivery_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO_Model',
            fields=[
                ('po_number', models.CharField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField()),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgement_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.vender_model')),
            ],
        ),
    ]
