# Generated by Django 5.0.4 on 2024-05-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_po_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_model',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vender_model',
            name='average_response_time',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vender_model',
            name='fulfillment_rate',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vender_model',
            name='quality_rating_avg',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Performance_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(max_length=60, null=True)),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.vender_model')),
            ],
        ),
    ]
