# Generated by Django 5.0.4 on 2024-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_alter_po_model_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_model',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='po_model',
            name='acknowledgement_date',
            field=models.DateTimeField(null=True),
        ),
    ]
