# Generated by Django 5.0.4 on 2024-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_alter_performance_model_quality_rating_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_model',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performance_model',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
    ]
