# Generated by Django 5.0.4 on 2024-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_alter_performance_model_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender_model',
            name='quality_rating_avg',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
