# Generated by Django 5.0.4 on 2024-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_alter_vender_model_quality_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_model',
            name='po_number',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vender_model',
            name='vender_code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
