# Generated by Django 5.0.4 on 2024-05-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_alter_po_model_po_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='po_model',
            old_name='acknowledgement_date',
            new_name='acknowledgment_date',
        ),
    ]
